---
/*/diving_node:
  ros__parameters:
    view_rate: 0.1
    model_rate: 0.1
    controller_rate: 0.1
    vbs_pid_kp: 40.0
    vbs_pid_ki: 5.0
    vbs_pid_kd: 1.0
    vbs_pid_kaw: 1.0
    vbs_u_neutral: 50.0
    vbs_u_min: 0.0
    vbs_u_max: 100.0
    lcg_pid_kp: 40.0
    lcg_pid_ki: 5.0
    lcg_pid_kd: 1.0
    lcg_pid_kaw: 1.0
    lcg_u_neutral: 50.0
    lcg_u_min: 0.0
    lcg_u_max: 100.0
    tv_pid_kp: 2.5
    tv_pid_ki: 0.25
    tv_pid_kd: 0.5
    tv_pid_kaw: 1.0
    tv_u_neutral: 0.0
    tv_u_min: -0.122173
    tv_u_max: 0.122173
    yaw_pid_kp: 2.5
    yaw_pid_ki: 0.25
    yaw_pid_kd: 0.5
    yaw_pid_kaw: 1.0
    yaw_u_neutral: 0.0
    yaw_u_min: -0.122173
    yaw_u_max: 0.122173
    rpm_u_neutral: 0.0
    rpm_u_min: -400.0
    rpm_u_max: 1500.0
    max_dive_pitch: 0.349
